# Tells the Maven wrapper which Maven version to download & use.
# First ./mvnw run downloads this into ~/.m2/wrapper, then reuses it.
wrapperVersion=3.3.2
distributionType=only-script
distributionUrl=https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.9.9/apache-maven-3.9.9-bin.zip
